### ISSUE TITLE
Add Vulnerability Assessment using OWASP Zap

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/scan-websites#11]
Lambda invoked by API Gateway which will result in launching a ECS task that will dynamically scan the URL for security vulnerabilities using OWASP Zap

**Comment by dj2** [comment]
Will this work similar to other tools where you can provide a list of URLs and specify if you want to crawl the website? Or, does it only run on a single page at a time?

**Comment by mohamed-cds** [comment]
> Will this work similar to other tools where you can provide a list of URLs and specify if you want to crawl the website? Or, does it only run on a single page at a time?

It'll get a list of discovered URL's for a specific app and will scan them as a group and provide a single report
