### ISSUE TITLE
Replace slowapi rate limiting implementation with WAF ruleset once available

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/scan-websites#111]
Rate limit introduced [here](https://github.com/cds-snc/scan-websites/pull/109). 

Implementation example AWS WAF rate limit.

https://stackoverflow.com/questions/65252674/when-using-terraform-with-aws-how-can-i-set-a-rate-limit-on-a-specific-uri-path

**Comment by patheard** [comment]
Related #142
