### ISSUE TITLE
Terraform: add checkov security scan GitHub Workflow

### ISSUE THREAD

**Issue by patheard** [cds-snc/scan-websites#132]
The majority of the fixes should be the same as those applied to the ListManager:
* cds-snc/list-manager#80
* cds-snc/list-manager#81

**Comment by dj2** [comment]
Checkov is setup to run already, there is an ignore file at https://github.com/cds-snc/scan-websites/blob/main/terragrunt/.checkov.yml where we need to work through the ignored entries.

Checkov is run by `make lint` so should be caught by the lint bot already.

**Comment by patheard** [comment]
Ah perfect, then it should just be a matter of adding the `terragrunt` folder to the matric for the `ci_code.yml` workflow:
https://github.com/cds-snc/scan-websites/blob/main/.github/workflows/ci_code.yml#L30

**Comment by dj2** [comment]
Can we just remove the matrix? The top level makefile has all the same commands so we don't really need the matrix do we?

**Comment by patheard** [comment]
I'll give it a shot while I'm making the change.
