### ISSUE TITLE
Add RDS Proxy + RDS Terraform

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/scan-websites#14]
We have a local DB, now we need on in the cloud. To achieve that we need to add TF for an RDS proxy and RDS instance and hook that into the lambda with `SQLALCHEMY_DATABASE_URI`. We also need a way to run migrations in the cloud, most likely by running `alembic` with an AWS cli invoke command after deploy.

**Comment by CalvinRodo** [comment]
Closed by many many PRs
