### ISSUE TITLE
New scanner: GitHub quality

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/scan-websites#140]
I would like to point the app at a public or private GitHub URL and learn the following:

- Are we using GitHub actions for CI?
- Are we using the best practice GitHub actions (s3 backup etc)?
- % of commits to main with code reviewed in the past 10 commits?
- Is a CDS approved license being used? (OSI license)
- Is Snyk (other static analysis tool) installed?
- Is the main branch protected?
- Does it have the required files (Security.MD, Code_of_conduct.MD)
- Is it using the CDS .github base repo?
- Is it public?
- Are PR Reviews Required
- Is CodeQL or LGTM enabled

Anything else?

**Comment by CalvinRodo** [comment]
Required PR Review

**Comment by patheard** [comment]
Golang example that @CalvinRodo worked on back at ESDC:
https://github.com/CalvinRodo/GithubComplianceCheck

**Comment by CalvinRodo** [comment]
Closing this cuz max has already done this
