### ISSUE TITLE
.devcontainer - Platform Dependent Terragrunt Hash

### ISSUE THREAD

**Issue by ShadeWyrm** [cds-snc/scan-websites#343]
With Devs having differing hardware, need to tweak the Terragrunt download/hash to be variable based on the platform of the Dev. 

Shouldn't default to just amd64.

See TERRAGRUNT_CHECKSUM in docker-compose.yml

**Comment by mohamed-cds** [comment]
thanks for the issue @ShadeWyrm. Welcome to the scan-websites party 🎉 . The benefit of our devcontainers is that no matter what the underlying infrastructure is we're all running vscode using the same architecture. As long as the windows/osx/linux machine has docker, the devcontainers should behave exactly the same when launched in vscode

**Comment by mohamed-cds** [comment]
TIL; had no idea it did that!
