### ISSUE TITLE
Store A11yReport

### ISSUE THREAD

**Issue by maxneuvians** [cds-snc/scan-websites#63]
Based on the model proposed in #9, save the axe-core report to the DB. We can assume that each report will have the following top level keys:

```
{
"url": "ex. https://digital.canada.ca",
"id": "UUIDv4",
"report": { ... }
}
```

with the URL and ID being injected through the crawler here: https://github.com/cds-snc/scan-websites/blob/main/api/crawler/crawler.py#L34 and here: https://github.com/cds-snc/scan-websites/blob/main/api/pub_sub/pub_sub.py#L16

Currently there is no way to directly inject a URL and ID into the axe-core pub-sub from the API that is not the crawler and something that needs to be addressed.

This issue should also extract the content of the report and save the relevant data as a summary. An example of that summary can be found here https://github.com/cds-snc/a11y-tools/blob/main/processing/persist-lambda/src/impl.ts#L148-L156 although this should inspire more than anything else.

Attached is a sample JSON of the an axe-core report.

[sample.json.txt](https://github.com/cds-snc/scan-websites/files/6983243/sample.json.txt)

**Comment by dj2** [comment]
Also `job_id` should be stored for the report so we can link all reports in a given job.
