### ISSUE TITLE
Fix skipped checkov lints and remove config file.

### ISSUE THREAD

**Issue by dj2** [cds-snc/scan-websites#72]
In order to enable checkov several of the checks were disabled. They should be enabled and the terragrunt/.checkov.yml file removed.

  - [ ] CKV_AWS_18
  - [ ] CKV_AWS_21
  - [ ] CKV_AWS_50
  - [ ] CKV_AWS_59
  - [ ] CKV_AWS_73
  - [ ] CKV_AWS_76
  - [ ] CKV_AWS_108
  - [ ] CKV_AWS_109
  - [ ] CKV_AWS_111
  - [ ] CKV_AWS_115
  - [ ] CKV_AWS_116
  - [ ] CKV_AWS_117
  - [ ] CKV_AWS_120
  - [ ] CKV_AWS_136
  - [ ] CKV_AWS_144
  - [ ] CKV_AWS_145
  - [ ] CKV2_AWS_4
  - [ ] CKV2_AWS_5
  - [ ] CKV2_AWS_29

**Comment by patheard** [comment]
Being fixed as part of #132
