### ISSUE TITLE
Zap lambda: Migrate to reading grouped requests (URL's) via Job id

### ISSUE THREAD

**Issue by mohamed-cds** [cds-snc/scan-websites#73]
JOB_Id which is the same for all of the URLs from a given request. So we can tie all of the things that are run from a given request together.

**Comment by dj2** [comment]
I'm going to add some comments to #9 as it needs to be updated slightly I think.

**Comment by dj2** [comment]
Actually, nm, I think `job_id` would be `scan_id` ...

**Comment by mohamed-cds** [comment]
scan_id & report_id's are being used to group results.
